// ─────────────────────────────────────────────
// TYPES
// ─────────────────────────────────────────────

export type Sector = "Commercial" | "Residential" | "Government" | "Industrial" | "Infrastructure";
export type Status = "Completed" | "Ongoing" | "Landmark";

export interface Project {
  id: string;
  slug: string;
  name: string;
  location: string;
  sector: Sector;
  status: Status;
  value: string;
  area: string;
  duration: string;
  year: string;
  image: string;           // main hero image
  images: string[];        // gallery images (you can add more later)
  description: string;
  featured: boolean;
  
  // NEW FIELDS
  client: string;
  clientTitle: string;
  brief: string;
  challenge: string;
  solution: string;
  outcome: string;
  outcomeHighlight: string;
  testimonial: string;
  testimonialAuthor: string;
  testimonialTitle: string;
  services: string[];
  teamSize: string;
  completionDate: string;
  architect?: string;
  structuralEngineer?: string;
  keyMetrics: { label: string; value: string }[];
}

// ─────────────────────────────────────────────
// DATA
// ─────────────────────────────────────────────

export const projects: Project[] = [
  {
    id: "p01",
    slug: "notgate-towers",
    name: "NotGate Towers",
    location: "Victoria Island, Lagos",
    sector: "Commercial",
    status: "Landmark",
    value: "₦12.8B",
    area: "47,000 sqm",
    duration: "18 Months",
    year: "2022",
    image: "/images/projects/notgate-towers.jpeg",
    images: ["/images/projects/notgate-towers.jpeg"],
    description: "A landmark twin-tower complex redefining the Lagos skyline with Class-A commercial and retail floors.",
    featured: true,
    client: "Lighthouse Properties Ltd",
    clientTitle: "Real Estate Development",
    brief: "NOTGATE was commissioned to design and deliver a twin-tower commercial complex on one of Victoria Island's last premium plots. The brief demanded Class-A specifications, LEED-aligned systems, and completion within 18 months.",
    challenge: "The site's proximity to the Lagos lagoon required specialised deep piling — over 1,200 bored piles to bedrock. Coordinating 6 simultaneous subcontractor streams while maintaining schedule demanded NOTGATE's full multi-project management system. Additionally, the client required uninterrupted power systems and a fibre-optic backbone capable of supporting 10,000 concurrent users.",
    solution: "NOTGATE deployed its proprietary deep-piling methodology using a combination of continuous flight auger and bored cast-in-situ techniques. A dedicated project war room with real-time drone monitoring and BIM coordination kept all 6 subcontractor streams aligned. A 2.5MVA backup power plant and redundant fibre network were installed to future-proof the towers.",
    outcome: "The towers were handed over ahead of schedule and became 100% tenanted within 4 months of completion. Total delivered value came to",
    outcomeHighlight: "₦12.8B — exceeding projections by 11%.",
    testimonial: "NOTGATE delivered something that didn't just meet the brief — it surpassed everything we imagined for this site. The quality of finish, the speed of delivery, and the professionalism of the team set a new standard for commercial development in Lagos.",
    testimonialAuthor: "Managing Director",
    testimonialTitle: "Lighthouse Properties Ltd",
    services: ["Design & Build", "Deep Piling", "MEP Engineering", "Project Management", "Interior Fit-Out"],
    teamSize: "340 workers at peak",
    completionDate: "December 2022",
    architect: "Adeyemi Associates",
    structuralEngineer: "NOTGATE Structural Division",
    keyMetrics: [
      { label: "Bored Piles", value: "1,200+" },
      { label: "Floors", value: "32" },
      { label: "Parking Bays", value: "480" },
      { label: "LEED Points", value: "68" },
    ],
  },
  {
    id: "p02",
    slug: "abuja-secretariat",
    name: "Abuja Federal Secretariat Annex",
    location: "Central Business District, Abuja",
    sector: "Government",
    status: "Completed",
    value: "₦8.4B",
    area: "31,200 sqm",
    duration: "24 Months",
    year: "2021",
    image: "/images/projects/abuja-secretariat.jpg",
    images: ["/images/projects/abuja-secretariat.jpg"],
    description: "Purpose-built federal office complex housing six ministries, engineered for longevity and state security.",
    featured: false,
    client: "Federal Ministry of Works & Housing",
    clientTitle: "Federal Government of Nigeria",
    brief: "The Federal Government required a modern, secure annex to decongest the existing secretariat complex. The building needed to house six ministries with independent access control, blast-resistant design, and 50-year structural lifespan specifications.",
    challenge: "Government procurement timelines are notoriously complex. NOTGATE had to navigate 14 approval stages across 6 agencies while maintaining construction momentum. Security clearances for all 340 workers, blast-resistant glazing, and a SCIF-level data centre added layers of technical complexity.",
    solution: "NOTGATE assigned a dedicated government liaison team to pre-emptively manage approvals. The structure was designed with progressive collapse resistance per GSA standards. A modular construction approach allowed interior fit-out to begin while exterior works continued, compressing the programme by 3 months.",
    outcome: "Delivered on budget and 6 weeks ahead of the contractual completion date. The complex now houses over 2,400 civil servants and has become the template for future federal office construction across Nigeria.",
    outcomeHighlight: "₦8.4B — on budget, ahead of schedule.",
    testimonial: "NOTGATE understood the unique demands of government construction. Their ability to maintain momentum through our approval processes while never compromising on quality was remarkable.",
    testimonialAuthor: "Permanent Secretary",
    testimonialTitle: "Federal Ministry of Works & Housing",
    services: ["Design & Build", "Blast-Resistant Engineering", "Security Systems", "Interior Fit-Out", "Landscaping"],
    teamSize: "280 workers at peak",
    completionDate: "August 2021",
    architect: "Federal Architects Consortium",
    structuralEngineer: "NOTGATE Structural Division",
    keyMetrics: [
      { label: "Ministries", value: "6" },
      { label: "Civil Servants", value: "2,400+" },
      { label: "Lifespan", value: "50 Years" },
      { label: "Approval Stages", value: "14" },
    ],
  },
  {
    id: "p03",
    slug: "lekki-coastal",
    name: "Lekki Coastal Residences",
    location: "Lekki Phase 2, Lagos",
    sector: "Residential",
    status: "Completed",
    value: "₦5.9B",
    area: "22,400 sqm",
    duration: "16 Months",
    year: "2023",
    image: "/images/projects/lekki-residences.jpeg",
    images: ["/images/projects/lekki-residences.jpeg"],
    description: "240-unit premium residential estate with smart-home integration and waterfront access.",
    featured: false,
    client: "Coastal Living Developments",
    clientTitle: "Private Developer",
    brief: "Create a 240-unit waterfront residential estate that would set a new benchmark for luxury living in Lagos. Each unit required smart-home integration, private balconies with lagoon views, and a central clubhouse with marina access.",
    challenge: "The site sat on reclaimed land with poor soil bearing capacity. Standard foundations would settle unevenly. Additionally, the client demanded that 40% of units be ready for handover within 10 months to satisfy pre-sales commitments.",
    solution: "NOTGATE designed a raft foundation system with geotextile reinforcement and vibro-compaction of the subsoil. A phased construction strategy delivered the first 96 units in 10 months while the remaining 144 units followed 6 weeks later. Smart-home infrastructure was pre-installed during the shell phase to avoid retrofit disruption.",
    outcome: "All 240 units were sold out within 8 weeks of launch. The estate achieved a 98% occupancy rate within 3 months and has become one of the most sought-after addresses on the Lekki peninsula.",
    outcomeHighlight: "100% sold out in 8 weeks.",
    testimonial: "NOTGATE turned a challenging site into one of Lagos' most desirable addresses. Their phased delivery strategy saved our pre-sales programme and the quality speaks for itself.",
    testimonialAuthor: "CEO",
    testimonialTitle: "Coastal Living Developments",
    services: ["Design & Build", "Geotechnical Engineering", "Smart-Home Integration", "Landscape Architecture", "Marina Construction"],
    teamSize: "190 workers at peak",
    completionDate: "March 2023",
    architect: "Studio Lekki",
    structuralEngineer: "NOTGATE Structural Division",
    keyMetrics: [
      { label: "Units", value: "240" },
      { label: "Occupancy", value: "98%" },
      { label: "Sell-Out Time", value: "8 Weeks" },
      { label: "Marina Berths", value: "24" },
    ],
  },
  {
    id: "p04",
    slug: "kano-industrial",
    name: "Kano Industrial Gateway",
    location: "Sharada Phase 3, Kano",
    sector: "Industrial",
    status: "Completed",
    value: "₦6.2B",
    area: "85,000 sqm",
    duration: "20 Months",
    year: "2020",
    image: "/images/projects/kano-industrial.jpg",
    images: ["/images/projects/kano-industrial.jpg"],
    description: "Integrated industrial park with 14 warehousing bays, logistics hub, and dedicated power infrastructure.",
    featured: false,
    client: "Northern Logistics Consortium",
    clientTitle: "Industrial Consortium",
    brief: "Build a modern industrial park to serve as the primary distribution hub for Northern Nigeria. The facility needed 14 warehousing bays, a central logistics office, cold storage, and a dedicated 1MVA power substation.",
    challenge: "Kano's extreme temperature swings — from 15°C in harmattan to 45°C in dry season — demanded specialised thermal engineering. The site also had no existing grid connection, requiring NOTGATE to build power infrastructure from scratch while construction was ongoing.",
    solution: "NOTGATE installed a hybrid cooling system with evaporative cooling for the dry season and conventional HVAC for the wet season. A 1MVA gas-powered substation was commissioned 4 months ahead of the main build to power construction tools and then transition seamlessly to facility operations. Reflective roofing and insulated wall panels reduced cooling loads by 35%.",
    outcome: "The park became operational 3 months ahead of schedule and now handles over 12,000 TEU annually. Energy costs are 40% below comparable facilities due to the hybrid power and cooling design.",
    outcomeHighlight: "12,000+ TEU handled annually.",
    testimonial: "NOTGATE didn't just build us a warehouse complex — they built us a competitive advantage. The energy efficiency alone has transformed our operating costs.",
    testimonialAuthor: "Chairman",
    testimonialTitle: "Northern Logistics Consortium",
    services: ["Design & Build", "Power Infrastructure", "Cold Storage Engineering", "Logistics Planning", "Thermal Engineering"],
    teamSize: "220 workers at peak",
    completionDate: "November 2020",
    architect: "NOTGATE Industrial Design",
    structuralEngineer: "NOTGATE Structural Division",
    keyMetrics: [
      { label: "Warehousing Bays", value: "14" },
      { label: "Power Capacity", value: "1MVA" },
      { label: "Annual TEU", value: "12,000+" },
      { label: "Energy Savings", value: "40%" },
    ],
  },
  {
    id: "p05",
    slug: "badagry-overpass",
    name: "Lagos–Badagry Expressway Overpass",
    location: "Mile 2, Lagos",
    sector: "Infrastructure",
    status: "Completed",
    value: "₦4.1B",
    area: "1.8 km span",
    duration: "14 Months",
    year: "2019",
    image: "/images/projects/badagry-overpass.jpg",
    images: ["/images/projects/badagry-overpass.jpg"],
    description: "Eight-lane grade-separated interchange relieving one of West Africa's most congested arterial routes.",
    featured: false,
    client: "Lagos State Ministry of Transportation",
    clientTitle: "State Government",
    brief: "Design and construct an eight-lane grade-separated interchange at Mile 2 to eliminate the notorious bottleneck on the Lagos-Badagry corridor. The project had to be completed without fully closing the existing expressway.",
    challenge: "Mile 2 is one of the busiest intersections in West Africa, handling over 250,000 vehicles daily. Full closure was impossible. The existing road sat on poor alluvial soil requiring deep pile foundations for the overpass piers. Night work restrictions in residential areas further compressed the working window.",
    solution: "NOTGATE employed a staged construction methodology, maintaining 4 lanes of traffic throughout the build. Pre-cast segmental construction for the overpass deck allowed assembly during off-peak hours. 48 deep piles were driven using silent piling to minimise noise disruption. The entire structure was built in 14 months with zero full closures.",
    outcome: "Traffic flow through Mile 2 improved by 65%. Journey times to Badagry were reduced from 4 hours to 90 minutes during peak periods. The interchange has handled over 100 million vehicle crossings with zero structural maintenance required.",
    outcomeHighlight: "65% traffic flow improvement.",
    testimonial: "NOTGATE achieved what many thought was impossible — building a major interchange while keeping the road open. The result has transformed the daily commute for millions of Lagosians.",
    testimonialAuthor: "Commissioner for Transportation",
    testimonialTitle: "Lagos State Government",
    services: ["Civil Engineering", "Traffic Management", "Pre-cast Construction", "Deep Piling", "Road Surfacing"],
    teamSize: "160 workers at peak",
    completionDate: "June 2019",
    architect: "N/A",
    structuralEngineer: "NOTGATE Civil & Structural",
    keyMetrics: [
      { label: "Daily Vehicles", value: "250,000+" },
      { label: "Deep Piles", value: "48" },
      { label: "Traffic Improvement", value: "65%" },
      { label: "Full Closures", value: "0" },
    ],
  },
  {
    id: "p06",
    slug: "heritage-court",
    name: "Heritage Court Ikoyi",
    location: "Old Ikoyi, Lagos",
    sector: "Residential",
    status: "Ongoing",
    value: "₦7.3B",
    area: "18,600 sqm",
    duration: "22 Months",
    year: "2024",
    image: "/images/projects/heritage-court.jpg",
    images: ["/images/projects/heritage-court.jpg"],
    description: "Ultra-luxury low-rise residences set within 4 acres of landscaped grounds in Lagos' most prestigious address.",
    featured: false,
    client: "Heritage Properties Ltd",
    clientTitle: "Luxury Developer",
    brief: "Create 18 ultra-luxury residences on 4 acres in Old Ikoyi, Lagos' most exclusive neighbourhood. Each residence must feature private pools, smart-home systems, and finishes comparable to Mayfair or Upper East Side standards.",
    challenge: "Old Ikoyi has strict height restrictions and preservation guidelines. The site is surrounded by heritage buildings requiring vibration monitoring during foundation works. The client also demanded that no two residences share the same floor plan — each must be architecturally unique.",
    solution: "NOTGATE designed 18 individually configured residences using a modular architectural system that allowed unique layouts from standardised structural elements. Real-time vibration monitoring with automatic shutdown triggers protected neighbouring heritage structures. A dedicated materials procurement team sourced Italian marble, German kitchen systems, and bespoke timber joinery directly from European manufacturers.",
    outcome: "Currently 78% complete with superstructure finished on all 18 units. Pre-sales have reached 94% at an average price point of ₦450M per unit — the highest in Ikoyi for a new-build development.",
    outcomeHighlight: "94% pre-sold at ₦450M average.",
    testimonial: "NOTGATE has elevated the standard of residential construction in Nigeria. The attention to detail, the bespoke finishes, and the respect for our heritage neighbours have been exceptional.",
    testimonialAuthor: "Development Director",
    testimonialTitle: "Heritage Properties Ltd",
    services: ["Design & Build", "Heritage-Sensitive Construction", "Bespoke Interior Fit-Out", "Smart-Home Integration", "Landscape Architecture"],
    teamSize: "260 workers at peak",
    completionDate: "Expected Q4 2024",
    architect: "David Adjaye Associates (Consultant)",
    structuralEngineer: "NOTGATE Structural Division",
    keyMetrics: [
      { label: "Residences", value: "18" },
      { label: "Pre-Sales", value: "94%" },
      { label: "Avg Price", value: "₦450M" },
      { label: "Completion", value: "78%" },
    ],
  },
  {
    id: "p07",
    slug: "ph-trade-centre",
    name: "Port Harcourt Trade Centre",
    location: "GRA Phase 2, Port Harcourt",
    sector: "Commercial",
    status: "Completed",
    value: "₦3.8B",
    area: "14,000 sqm",
    duration: "12 Months",
    year: "2021",
    image: "/images/projects/ph-trade-centre.jpg",
    images: ["/images/projects/ph-trade-centre.jpg"],
    description: "A six-floor mixed-use trade centre anchoring the city's new commercial district with retail and office floors.",
    featured: false,
    client: "Rivers State Investment Corporation",
    clientTitle: "State Investment Body",
    brief: "Deliver a mixed-use trade centre in Port Harcourt's emerging GRA Phase 2 commercial district. The building needed ground-floor retail, four floors of Grade-B office space, and a rooftop conference facility with city views.",
    challenge: "Port Harcourt's high humidity and rainfall (over 4,000mm annually) demanded exceptional waterproofing and corrosion protection. The client required completion in 12 months to coincide with the state's investment summit, leaving no schedule flexibility.",
    solution: "NOTGATE specified marine-grade aluminium cladding and a multi-layer waterproofing system with 25-year guarantees. A fast-track construction sequence saw the shell completed in 7 months, allowing 5 months for MEP and fit-out. The rooftop conference centre was pre-fabricated off-site and craned into position in a single day.",
    outcome: "Handed over 2 weeks before the investment summit. The trade centre achieved 85% occupancy within 6 months and has become the anchor tenant for the new GRA Phase 2 district.",
    outcomeHighlight: "85% occupancy in 6 months.",
    testimonial: "NOTGATE delivered our flagship investment project on an impossibly tight timeline. The building quality and the speed of delivery have attracted significant follow-on investment to the district.",
    testimonialAuthor: "Managing Director",
    testimonialTitle: "Rivers State Investment Corporation",
    services: ["Design & Build", "Fast-Track Construction", "Waterproofing Systems", "MEP Engineering", "Rooftop Pre-fabrication"],
    teamSize: "150 workers at peak",
    completionDate: "October 2021",
    architect: "PH Architects Ltd",
    structuralEngineer: "NOTGATE Structural Division",
    keyMetrics: [
      { label: "Floors", value: "6" },
      { label: "Occupancy", value: "85%" },
      { label: "Waterproofing", value: "25yr" },
      { label: "Shell Duration", value: "7 Mo" },
    ],
  },
  {
    id: "p08",
    slug: "enugu-hospital",
    name: "Enugu State Hospital Complex",
    location: "Independence Layout, Enugu",
    sector: "Government",
    status: "Completed",
    value: "₦5.5B",
    area: "27,000 sqm",
    duration: "26 Months",
    year: "2020",
    image: "/images/projects/enugu-hospital.jpg",
    images: ["/images/projects/enugu-hospital.jpg"],
    description: "500-bed tertiary hospital built to WHO standards, delivering critical healthcare infrastructure to South-East Nigeria.",
    featured: false,
    client: "Enugu State Ministry of Health",
    clientTitle: "State Government",
    brief: "Construct a 500-bed tertiary hospital to serve as the referral centre for South-East Nigeria. The facility needed surgical theatres, ICU, radiology, maternity, and isolation wards — all built to WHO standards for infection control and patient flow.",
    challenge: "Healthcare construction demands precision in MEP systems, infection control, and medical gas infrastructure. The site had limited access for large equipment, and the state required phased handover so emergency services could begin while construction continued.",
    solution: "NOTGATE implemented a clean-build protocol with dedicated infection-control officers on site 24/7. Medical gas pipelines, HVAC with HEPA filtration, and uninterruptible power systems were installed by certified specialists. A phased handover saw the emergency department open 8 months before the main hospital, serving the community during the final construction phase.",
    outcome: "The hospital now serves over 2,000 outpatients daily and has performed over 8,000 surgeries in its first three years. It is the first WHO-standard tertiary facility in South-East Nigeria.",
    outcomeHighlight: "2,000+ outpatients daily.",
    testimonial: "NOTGATE built us more than a hospital — they built us a lifeline for the people of Enugu. The quality of construction and the phased delivery approach were exemplary.",
    testimonialAuthor: "Commissioner for Health",
    testimonialTitle: "Enugu State Government",
    services: ["Design & Build", "Medical Gas Systems", "Infection Control", "HEPA HVAC", "Phased Handover"],
    teamSize: "310 workers at peak",
    completionDate: "March 2020",
    architect: "Health Facilities Design Group",
    structuralEngineer: "NOTGATE Structural Division",
    keyMetrics: [
      { label: "Beds", value: "500" },
      { label: "Daily Outpatients", value: "2,000+" },
      { label: "Surgeries (3yr)", value: "8,000+" },
      { label: "Theatres", value: "8" },
    ],
  },
  {
    id: "p09",
    slug: "accra-business-park",
    name: "Accra Business Park",
    location: "Airport City, Accra, Ghana",
    sector: "Commercial",
    status: "Completed",
    value: "₦4.6B",
    area: "19,500 sqm",
    duration: "18 Months",
    year: "2022",
    image: "/images/projects/accra-business-park.jpg",
    images: ["/images/projects/accra-business-park.jpg"],
    description: "NOTGATE's first pan-African landmark — Grade-A offices designed for multinational tenants adjacent to Kotoka Airport.",
    featured: false,
    client: "Airport City Developments Ghana",
    clientTitle: "Ghanaian Developer",
    brief: "NOTGATE's first project outside Nigeria — a Grade-A office complex in Accra's Airport City, designed to attract multinational tenants requiring international-standard facilities adjacent to Kotoka International Airport.",
    challenge: "Operating in a new country meant navigating Ghanaian building codes, import regulations, and a different labour market. The client required LEED Gold certification and a 15-month programme — 3 months shorter than NOTGATE's typical commercial timeline.",
    solution: "NOTGATE established a Ghana subsidiary 6 months before breaking ground, hiring local talent and partnering with Ghanaian subcontractors. A dedicated import-logistics team pre-cleared all materials to avoid port delays. The project was delivered using NOTGATE's Nigerian quality standards adapted for Ghanaian regulatory requirements.",
    outcome: "100% leased to multinational tenants including 3 Fortune 500 companies within 5 months of completion. The project established NOTGATE as a credible pan-African contractor and won the Ghana Property Awards 'Development of the Year 2022'.",
    outcomeHighlight: "100% leased to multinationals in 5 months.",
    testimonial: "NOTGATE brought Nigerian scale and speed to Ghana with local sensitivity. They understood our market, our regulations, and our ambition to create a world-class business district.",
    testimonialAuthor: "CEO",
    testimonialTitle: "Airport City Developments Ghana",
    services: ["Design & Build", "Cross-Border Logistics", "LEED Certification", "Multinational Fit-Out", "Local Partnership"],
    teamSize: "200 workers at peak",
    completionDate: "April 2022",
    architect: "Airport City Design Studio",
    structuralEngineer: "NOTGATE Ghana + Local Partners",
    keyMetrics: [
      { label: "Fortune 500 Tenants", value: "3" },
      { label: "Lease-Up Time", value: "5 Mo" },
      { label: "LEED Rating", value: "Gold" },
      { label: "Award", value: "Dev of Year" },
    ],
  },
  {
    id: "p10",
    slug: "warri-petrochemical",
    name: "Warri Petrochemical Storage Hub",
    location: "Effurun, Delta State",
    sector: "Industrial",
    status: "Ongoing",
    value: "₦9.1B",
    area: "120,000 sqm",
    duration: "30 Months",
    year: "2024",
    image: "/images/projects/warri-petrochemical.jpg",
    images: ["/images/projects/warri-petrochemical.jpg"],
    description: "Bulk petrochemical storage facility with 28 pressurised tanks and full pipeline integration.",
    featured: false,
    client: "Delta Petrochemicals Ltd",
    clientTitle: "Petrochemical Operator",
    brief: "Construct a bulk petrochemical storage facility with 28 pressurised storage tanks, pipeline integration to the nearby refinery, and full fire-suppression and spill-containment systems. The facility must meet DPR and international API standards.",
    challenge: "Petrochemical construction requires extreme precision in welding, pressure testing, and safety systems. The site is in the Niger Delta with challenging logistics and security considerations. 28 pressurised tanks, each holding 5,000 metric tonnes, required specialised foundation design and seismic bracing.",
    solution: "NOTGATE partnered with a German tank manufacturer for the pressurised vessels and trained 60 local welders to ASME certification standards. A dedicated security perimeter with 24/7 monitoring was established before construction began. Foundation piles were driven to 35 metres to reach stable bedrock below the delta alluvium.",
    outcome: "Currently 65% complete with all 28 tank foundations finished and 18 tanks erected. The facility is on track for Q2 2025 commissioning and will become the largest private petrochemical storage hub in West Africa.",
    outcomeHighlight: "Largest private petrochemical hub in West Africa.",
    testimonial: "NOTGATE's approach to safety and precision in petrochemical construction is world-class. Their investment in training local welders to international standards has been particularly impressive.",
    testimonialAuthor: "Managing Director",
    testimonialTitle: "Delta Petrochemicals Ltd",
    services: ["Design & Build", "Pressure Vessel Installation", "Pipeline Integration", "Fire Suppression", "Spill Containment"],
    teamSize: "380 workers at peak",
    completionDate: "Expected Q2 2025",
    architect: "N/A",
    structuralEngineer: "NOTGATE Industrial + German Partners",
    keyMetrics: [
      { label: "Pressurised Tanks", value: "28" },
      { label: "Tank Capacity", value: "5,000 MT" },
      { label: "Foundation Depth", value: "35m" },
      { label: "Completion", value: "65%" },
    ],
  },
  {
    id: "p11",
    slug: "maitama-estate",
    name: "Maitama Premium Estate",
    location: "Maitama District, Abuja",
    sector: "Residential",
    status: "Completed",
    value: "₦3.2B",
    area: "11,400 sqm",
    duration: "10 Months",
    year: "2023",
    image: "/images/projects/maitama-estate.png",
    images: ["/images/projects/maitama-estate.png"],
    description: "36 executive detached villas with perimeter security, underground utilities, and private clubhouse.",
    featured: false,
    client: "Maitama Development Company",
    clientTitle: "Private Developer",
    brief: "Deliver 36 executive detached villas in Abuja's most exclusive district within 10 months. Each villa required 4 bedrooms, a private study, underground utilities, and access to a central clubhouse with pool and tennis courts.",
    challenge: "Maitama's strict planning regulations limited building height and mandated specific architectural styles. The 10-month timeline was aggressive for 36 individual units, and the client required that all underground utilities (power, water, sewage, fibre) be completed before any surface construction began.",
    solution: "NOTGATE employed a production-line approach with 6 construction teams each responsible for 6 villas, working in parallel. Underground utility tunnels were pre-fabricated in segments and installed using directional drilling to minimise surface disruption. A central concrete batching plant on site ensured consistent quality and eliminated delivery delays.",
    outcome: "All 36 villas were handed over within the 10-month programme. The estate sold out in 3 weeks and has become the benchmark for premium residential development in Abuja.",
    outcomeHighlight: "Sold out in 3 weeks.",
    testimonial: "NOTGATE's production-line methodology delivered 36 bespoke villas in 10 months without ever feeling like a mass-produced development. The quality is exceptional.",
    testimonialAuthor: "Chairman",
    testimonialTitle: "Maitama Development Company",
    services: ["Design & Build", "Underground Utilities", "Production-Line Construction", "Landscape Architecture", "Clubhouse Construction"],
    teamSize: "170 workers at peak",
    completionDate: "May 2023",
    architect: "Abuja Heritage Architects",
    structuralEngineer: "NOTGATE Structural Division",
    keyMetrics: [
      { label: "Villas", value: "36" },
      { label: "Sell-Out Time", value: "3 Weeks" },
      { label: "Construction Teams", value: "6" },
      { label: "Bedrooms", value: "4 Each" },
    ],
  },
  {
    id: "p12",
    slug: "ibadan-bridge",
    name: "Ibadan Ring Road Bridge",
    location: "Challenge–Toll Gate, Ibadan",
    sector: "Infrastructure",
    status: "Completed",
    value: "₦2.9B",
    area: "940 m span",
    duration: "11 Months",
    year: "2019",
    image: "/images/projects/ibadan-bridge.jpg",
    images: ["/images/projects/ibadan-bridge.jpg"],
    description: "Pre-stressed concrete bridge linking the western bypass and reducing inner-city transit time by 35%.",
    featured: false,
    client: "Oyo State Ministry of Works",
    clientTitle: "State Government",
    brief: "Construct a 940-metre pre-stressed concrete bridge to link Ibadan's western bypass with the Challenge-Toll Gate corridor, eliminating the need for vehicles to pass through the city centre.",
    challenge: "The bridge had to span a major river and existing road intersection with minimal disruption. Pre-stressed concrete requires precise tensioning and curing — any error compromises the entire structure. The state also required that the existing road remain open throughout construction.",
    solution: "NOTGATE used incremental launching for the bridge deck, pushing segments across from one abutment while maintaining traffic below. Pre-stressing cables were tensioned using computer-controlled jacks to ensure uniform force distribution. The river piers were founded on caissons sunk through 12 metres of alluvium to bedrock.",
    outcome: "The bridge reduced inner-city transit time by 35% and has handled over 50 million vehicle crossings with zero structural issues. It won the Nigerian Society of Engineers' 'Infrastructure Project of the Year 2019'.",
    outcomeHighlight: "35% transit time reduction.",
    testimonial: "NOTGATE built us a bridge that has transformed Ibadan's traffic flow. Their incremental launching technique kept the road open and the quality is outstanding.",
    testimonialAuthor: "Commissioner for Works",
    testimonialTitle: "Oyo State Government",
    services: ["Civil Engineering", "Pre-stressed Concrete", "Incremental Launching", "Caisson Foundations", "Road Surfacing"],
    teamSize: "140 workers at peak",
    completionDate: "September 2019",
    architect: "N/A",
    structuralEngineer: "NOTGATE Civil & Structural",
    keyMetrics: [
      { label: "Span", value: "940m" },
      { label: "Vehicle Crossings", value: "50M+" },
      { label: "Transit Reduction", value: "35%" },
      { label: "Award", value: "NSE 2019" },
    ],
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export function getRelatedProjects(currentSlug: string, limit = 3): Project[] {
  const current = getProjectBySlug(currentSlug);
  if (!current) return [];
  return projects
    .filter((p) => p.slug !== currentSlug && p.sector === current.sector)
    .slice(0, limit);
}